version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: torreserver
    container_name: torreserver
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

